### ISSUE TITLE
Implement splitValues to get values of INSERT INTO ... VALUES ... statement

### ISSUE THREAD

**Issue by keldrox** [jasny/persist-sql-query#5]
I would very much like this functionality to exist

thanks!!

**Comment by jasny** [comment]
Implemented in v3 (alpha1).

```
use Jasny\Persist\SQL\Query;

$query = new Query("INSERT INTO foo VALUES (1, 'test', 22), (2, 'bar', NULL)", 'mysql');
$values = $query->getValues(Query::UNQUOTE); // [ [1, 'test', 22], [2, 'bar', null] ]
```

_Please note that the project name has changed to `jasny/persist-sql-query` and the namespace has also changed.._

**Comment by keldrox** [comment]
getValues not working yet for an UPDATE query?

Thanks for your wonderful work

**Comment by jasny** [comment]
An update query doesn't have a `VALUES` section.  Use `getSet()` instead.
